modules.exports = [
  { name: 'Afghanistan',
    alpha: 'AF',
    alpha3: 'AFG',
    numeric: 4 },
  { name: 'Åland',
    alpha: 'AX',
    alpha3: 'ALA',
    numeric: 248 },
  { name: 'Albania',
    alpha: 'AL',
    alpha3: 'ALB',
    numeric: 8 },
  { name: 'Algeria',
    alpha: 'DZ',
    alpha3: 'DZA',
    numeric: 12 },
  { name: 'American Samoa',
    alpha: 'AS',
    alpha3: 'ASM',
    numeric: 16 },
  { name: 'Andorra',
    alpha: 'AD',
    alpha3: 'AND',
    numeric: 20 },
  { name: 'Angola',
    alpha: 'AO',
    alpha3: 'AGO',
    numeric: 24 },
  { name: 'Anguilla',
    alpha: 'AI',
    alpha3: 'AIA',
    numeric: 660 },
  { name: 'Antarctica',
    alpha: 'AQ',
    alpha3: 'ATA',
    numeric: 10 },
  { name: 'Antigua and Barbuda',
    alpha: 'AG',
    alpha3: 'ATG',
    numeric: 28 },
  { name: 'Argentina',
    alpha: 'AR',
    alpha3: 'ARG',
    numeric: 32 },
  { name: 'Armenia',
    alpha: 'AM',
    alpha3: 'ARM',
    numeric: 51 },
  { name: 'Aruba',
    alpha: 'AW',
    alpha3: 'ABW',
    numeric: 533 },
  { name: 'Australia',
    alpha: 'AU',
    alpha3: 'AUS',
    numeric: 36 },
  { name: 'Austria',
    alpha: 'AT',
    alpha3: 'AUT',
    numeric: 40 },
  { name: 'Azerbaijan',
    alpha: 'AZ',
    alpha3: 'AZE',
    numeric: 31 },
  { name: 'Bahamas',
    alpha: 'BS',
    alpha3: 'BHS',
    numeric: 44 },
  { name: 'Bahrain',
    alpha: 'BH',
    alpha3: 'BHR',
    numeric: 48 },
  { name: 'Bangladesh',
    alpha: 'BD',
    alpha3: 'BGD',
    numeric: 50 },
  { name: 'Barbados',
    alpha: 'BB',
    alpha3: 'BRB',
    numeric: 52 },
  { name: 'Belarus',
    alpha: 'BY',
    alpha3: 'BLR',
    numeric: 112 },
  { name: 'Belgium',
    alpha: 'BE',
    alpha3: 'BEL',
    numeric: 56 },
  { name: 'Belize',
    alpha: 'BZ',
    alpha3: 'BLZ',
    numeric: 84 },
  { name: 'Benin',
    alpha: 'BJ',
    alpha3: 'BEN',
    numeric: 204 },
  { name: 'Bermuda',
    alpha: 'BM',
    alpha3: 'BMU',
    numeric: 60 },
  { name: 'Bhutan',
    alpha: 'BT',
    alpha3: 'BTN',
    numeric: 64 },
  { name: 'Bolivia',
    alpha: 'BO',
    alpha3: 'BOL',
    numeric: 68 },
  { name: 'Bosnia and Herzegovina',
    alpha: 'BA',
    alpha3: 'BIH',
    numeric: 70 },
  { name: 'Botswana',
    alpha: 'BW',
    alpha3: 'BWA',
    numeric: 72 },
  { name: 'Bouvet Island',
    alpha: 'BV',
    alpha3: 'BVT',
    numeric: 74 },
  { name: 'Brazil',
    alpha: 'BR',
    alpha3: 'BRA',
    numeric: 76 },
  { name: 'British Indian Ocean Territory',
    alpha: 'IO',
    alpha3: 'IOT',
    numeric: 86 },
  { name: 'Brunei Darussalam',
    alpha: 'BN',
    alpha3: 'BRN',
    numeric: 96 },
  { name: 'Bulgaria',
    alpha: 'BG',
    alpha3: 'BGR',
    numeric: 100 },
  { name: 'Burkina Faso',
    alpha: 'BF',
    alpha3: 'BFA',
    numeric: 854 },
  { name: 'Burundi',
    alpha: 'BI',
    alpha3: 'BDI',
    numeric: 108 },
  { name: 'Cambodia',
    alpha: 'KH',
    alpha3: 'KHM',
    numeric: 116 },
  { name: 'Cameroon',
    alpha: 'CM',
    alpha3: 'CMR',
    numeric: 120 },
  { name: 'Canada',
    alpha: 'CA',
    alpha3: 'CAN',
    numeric: 124 },
  { name: 'Cape Verde',
    alpha: 'CV',
    alpha3: 'CPV',
    numeric: 132 },
  { name: 'Cayman Islands',
    alpha: 'KY',
    alpha3: 'CYM',
    numeric: 136 },
  { name: 'Central African Republic',
    alpha: 'CF',
    alpha3: 'CAF',
    numeric: 140 },
  { name: 'Chad',
    alpha: 'TD',
    alpha3: 'TCD',
    numeric: 148 },
  { name: 'Chile',
    alpha: 'CL',
    alpha3: 'CHL',
    numeric: 152 },
  { name: 'China',
    alpha: 'CN',
    alpha3: 'CHN',
    numeric: 156 },
  { name: 'Christmas Island',
    alpha: 'CX',
    alpha3: 'CXR',
    numeric: 162 },
  { name: 'Cocos (Keeling) Islands',
    alpha: 'CC',
    alpha3: 'CCK',
    numeric: 166 },
  { name: 'Colombia',
    alpha: 'CO',
    alpha3: 'COL',
    numeric: 170 },
  { name: 'Comoros',
    alpha: 'KM',
    alpha3: 'COM',
    numeric: 174 },
  { name: 'Congo (Brazzaville)',
    alpha: 'CG',
    alpha3: 'COG',
    numeric: 178 },
  { name: 'Congo (Kinshasa)',
    alpha: 'CD',
    alpha3: 'COD',
    numeric: 180 },
  { name: 'Cook Islands',
    alpha: 'CK',
    alpha3: 'COK',
    numeric: 184 },
  { name: 'Costa Rica',
    alpha: 'CR',
    alpha3: 'CRI',
    numeric: 188 },
  { name: 'Côte d\'Ivoire',
    alpha: 'CI',
    alpha3: 'CIV',
    numeric: 384 },
  { name: 'Croatia',
    alpha: 'HR',
    alpha3: 'HRV',
    numeric: 191 },
  { name: 'Cuba',
    alpha: 'CU',
    alpha3: 'CUB',
    numeric: 192 },
  { name: 'Cyprus',
    alpha: 'CY',
    alpha3: 'CYP',
    numeric: 196 },
  { name: 'Czech Republic',
    alpha: 'CZ',
    alpha3: 'CZE',
    numeric: 203 },
  { name: 'Denmark',
    alpha: 'DK',
    alpha3: 'DNK',
    numeric: 208 },
  { name: 'Djibouti',
    alpha: 'DJ',
    alpha3: 'DJI',
    numeric: 262 },
  { name: 'Dominica',
    alpha: 'DM',
    alpha3: 'DMA',
    numeric: 212 },
  { name: 'Dominican Republic',
    alpha: 'DO',
    alpha3: 'DOM',
    numeric: 214 },
  { name: 'Ecuador',
    alpha: 'EC',
    alpha3: 'ECU',
    numeric: 218 },
  { name: 'Egypt',
    alpha: 'EG',
    alpha3: 'EGY',
    numeric: 818 },
  { name: 'El Salvador',
    alpha: 'SV',
    alpha3: 'SLV',
    numeric: 222 },
  { name: 'Equatorial Guinea',
    alpha: 'GQ',
    alpha3: 'GNQ',
    numeric: 226 },
  { name: 'Eritrea',
    alpha: 'ER',
    alpha3: 'ERI',
    numeric: 232 },
  { name: 'Estonia',
    alpha: 'EE',
    alpha3: 'EST',
    numeric: 233 },
  { name: 'Ethiopia',
    alpha: 'ET',
    alpha3: 'ETH',
    numeric: 231 },
  { name: 'Falkland Islands',
    alpha: 'FK',
    alpha3: 'FLK',
    numeric: 238 },
  { name: 'Faroe Islands',
    alpha: 'FO',
    alpha3: 'FRO',
    numeric: 234 },
  { name: 'Fiji',
    alpha: 'FJ',
    alpha3: 'FJI',
    numeric: 242 },
  { name: 'Finland',
    alpha: 'FI',
    alpha3: 'FIN',
    numeric: 246 },
  { name: 'France',
    alpha: 'FR',
    alpha3: 'FRA',
    numeric: 250 },
  { name: 'French Guiana',
    alpha: 'GF',
    alpha3: 'GUF',
    numeric: 254 },
  { name: 'French Polynesia',
    alpha: 'PF',
    alpha3: 'PYF',
    numeric: 258 },
  { name: 'French Southern Lands',
    alpha: 'TF',
    alpha3: 'ATF',
    numeric: 260 },
  { name: 'Gabon',
    alpha: 'GA',
    alpha3: 'GAB',
    numeric: 266 },
  { name: 'Gambia',
    alpha: 'GM',
    alpha3: 'GMB',
    numeric: 270 },
  { name: 'Georgia',
    alpha: 'GE',
    alpha3: 'GEO',
    numeric: 268 },
  { name: 'Germany',
    alpha: 'DE',
    alpha3: 'DEU',
    numeric: 276 },
  { name: 'Ghana',
    alpha: 'GH',
    alpha3: 'GHA',
    numeric: 288 },
  { name: 'Gibraltar',
    alpha: 'GI',
    alpha3: 'GIB',
    numeric: 292 },
  { name: 'Greece',
    alpha: 'GR',
    alpha3: 'GRC',
    numeric: 300 },
  { name: 'Greenland',
    alpha: 'GL',
    alpha3: 'GRL',
    numeric: 304 },
  { name: 'Grenada',
    alpha: 'GD',
    alpha3: 'GRD',
    numeric: 308 },
  { name: 'Guadeloupe',
    alpha: 'GP',
    alpha3: 'GLP',
    numeric: 312 },
  { name: 'Guam',
    alpha: 'GU',
    alpha3: 'GUM',
    numeric: 316 },
  { name: 'Guatemala',
    alpha: 'GT',
    alpha3: 'GTM',
    numeric: 320 },
  { name: 'Guernsey',
    alpha: 'GG',
    alpha3: 'GGY',
    numeric: 831 },
  { name: 'Guinea',
    alpha: 'GN',
    alpha3: 'GIN',
    numeric: 324 },
  { name: 'Guinea-Bissau',
    alpha: 'GW',
    alpha3: 'GNB',
    numeric: 624 },
  { name: 'Guyana',
    alpha: 'GY',
    alpha3: 'GUY',
    numeric: 328 },
  { name: 'Haiti',
    alpha: 'HT',
    alpha3: 'HTI',
    numeric: 332 },
  { name: 'Heard and McDonald Islands',
    alpha: 'HM',
    alpha3: 'HMD',
    numeric: 334 },
  { name: 'Honduras',
    alpha: 'HN',
    alpha3: 'HND',
    numeric: 340 },
  { name: 'Hong Kong',
    alpha: 'HK',
    alpha3: 'HKG',
    numeric: 344 },
  { name: 'Hungary',
    alpha: 'HU',
    alpha3: 'HUN',
    numeric: 348 },
  { name: 'Iceland',
    alpha: 'IS',
    alpha3: 'ISL',
    numeric: 352 },
  { name: 'India',
    alpha: 'IN',
    alpha3: 'IND',
    numeric: 356 },
  { name: 'Indonesia',
    alpha: 'ID',
    alpha3: 'IDN',
    numeric: 360 },
  { name: 'Iran',
    alpha: 'IR',
    alpha3: 'IRN',
    numeric: 364 },
  { name: 'Iraq',
    alpha: 'IQ',
    alpha3: 'IRQ',
    numeric: 368 },
  { name: 'Ireland',
    alpha: 'IE',
    alpha3: 'IRL',
    numeric: 372 },
  { name: 'Isle of Man',
    alpha: 'IM',
    alpha3: 'IMN',
    numeric: 833 },
  { name: 'Israel',
    alpha: 'IL',
    alpha3: 'ISR',
    numeric: 376 },
  { name: 'Italy',
    alpha: 'IT',
    alpha3: 'ITA',
    numeric: 380 },
  { name: 'Jamaica',
    alpha: 'JM',
    alpha3: 'JAM',
    numeric: 388 },
  { name: 'Japan',
    alpha: 'JP',
    alpha3: 'JPN',
    numeric: 392 },
  { name: 'Jersey',
    alpha: 'JE',
    alpha3: 'JEY',
    numeric: 832 },
  { name: 'Jordan',
    alpha: 'JO',
    alpha3: 'JOR',
    numeric: 400 },
  { name: 'Kazakhstan',
    alpha: 'KZ',
    alpha3: 'KAZ',
    numeric: 398 },
  { name: 'Kenya',
    alpha: 'KE',
    alpha3: 'KEN',
    numeric: 404 },
  { name: 'Kiribati',
    alpha: 'KI',
    alpha3: 'KIR',
    numeric: 296 },
  { name: 'Korea, North',
    alpha: 'KP',
    alpha3: 'PRK',
    numeric: 408 },
  { name: 'Korea, South',
    alpha: 'KR',
    alpha3: 'KOR',
    numeric: 410 },
  { name: 'Kuwait',
    alpha: 'KW',
    alpha3: 'KWT',
    numeric: 414 },
  { name: 'Kyrgyzstan',
    alpha: 'KG',
    alpha3: 'KGZ',
    numeric: 417 },
  { name: 'Laos',
    alpha: 'LA',
    alpha3: 'LAO',
    numeric: 418 },
  { name: 'Latvia',
    alpha: 'LV',
    alpha3: 'LVA',
    numeric: 428 },
  { name: 'Lebanon',
    alpha: 'LB',
    alpha3: 'LBN',
    numeric: 422 },
  { name: 'Lesotho',
    alpha: 'LS',
    alpha3: 'LSO',
    numeric: 426 },
  { name: 'Liberia',
    alpha: 'LR',
    alpha3: 'LBR',
    numeric: 430 },
  { name: 'Libya',
    alpha: 'LY',
    alpha3: 'LBY',
    numeric: 434 },
  { name: 'Liechtenstein',
    alpha: 'LI',
    alpha3: 'LIE',
    numeric: 438 },
  { name: 'Lithuania',
    alpha: 'LT',
    alpha3: 'LTU',
    numeric: 440 },
  { name: 'Luxembourg',
    alpha: 'LU',
    alpha3: 'LUX',
    numeric: 442 },
  { name: 'Macau',
    alpha: 'MO',
    alpha3: 'MAC',
    numeric: 446 },
  { name: 'Macedonia',
    alpha: 'MK',
    alpha3: 'MKD',
    numeric: 807 },
  { name: 'Madagascar',
    alpha: 'MG',
    alpha3: 'MDG',
    numeric: 450 },
  { name: 'Malawi',
    alpha: 'MW',
    alpha3: 'MWI',
    numeric: 454 },
  { name: 'Malaysia',
    alpha: 'MY',
    alpha3: 'MYS',
    numeric: 458 },
  { name: 'Maldives',
    alpha: 'MV',
    alpha3: 'MDV',
    numeric: 462 },
  { name: 'Mali',
    alpha: 'ML',
    alpha3: 'MLI',
    numeric: 466 },
  { name: 'Malta',
    alpha: 'MT',
    alpha3: 'MLT',
    numeric: 470 },
  { name: 'Marshall Islands',
    alpha: 'MH',
    alpha3: 'MHL',
    numeric: 584 },
  { name: 'Martinique',
    alpha: 'MQ',
    alpha3: 'MTQ',
    numeric: 474 },
  { name: 'Mauritania',
    alpha: 'MR',
    alpha3: 'MRT',
    numeric: 478 },
  { name: 'Mauritius',
    alpha: 'MU',
    alpha3: 'MUS',
    numeric: 480 },
  { name: 'Mayotte',
    alpha: 'YT',
    alpha3: 'MYT',
    numeric: 175 },
  { name: 'Mexico',
    alpha: 'MX',
    alpha3: 'MEX',
    numeric: 484 },
  { name: 'Micronesia',
    alpha: 'FM',
    alpha3: 'FSM',
    numeric: 583 },
  { name: 'Moldova',
    alpha: 'MD',
    alpha3: 'MDA',
    numeric: 498 },
  { name: 'Monaco',
    alpha: 'MC',
    alpha3: 'MCO',
    numeric: 492 },
  { name: 'Mongolia',
    alpha: 'MN',
    alpha3: 'MNG',
    numeric: 496 },
  { name: 'Montenegro',
    alpha: 'ME',
    alpha3: 'MNE',
    numeric: 499 },
  { name: 'Montserrat',
    alpha: 'MS',
    alpha3: 'MSR',
    numeric: 500 },
  { name: 'Morocco',
    alpha: 'MA',
    alpha3: 'MAR',
    numeric: 504 },
  { name: 'Mozambique',
    alpha: 'MZ',
    alpha3: 'MOZ',
    numeric: 508 },
  { name: 'Myanmar',
    alpha: 'MM',
    alpha3: 'MMR',
    numeric: 104 },
  { name: 'Namibia',
    alpha: 'NA',
    alpha3: 'NAM',
    numeric: 516 },
  { name: 'Nauru',
    alpha: 'NR',
    alpha3: 'NRU',
    numeric: 520 },
  { name: 'Nepal',
    alpha: 'NP',
    alpha3: 'NPL',
    numeric: 524 },
  { name: 'Netherlands',
    alpha: 'NL',
    alpha3: 'NLD',
    numeric: 528 },
  { name: 'Netherlands Antilles',
    alpha: 'AN',
    alpha3: 'ANT',
    numeric: 530 },
  { name: 'New Caledonia',
    alpha: 'NC',
    alpha3: 'NCL',
    numeric: 540 },
  { name: 'New Zealand',
    alpha: 'NZ',
    alpha3: 'NZL',
    numeric: 554 },
  { name: 'Nicaragua',
    alpha: 'NI',
    alpha3: 'NIC',
    numeric: 558 },
  { name: 'Niger',
    alpha: 'NE',
    alpha3: 'NER',
    numeric: 562 },
  { name: 'Nigeria',
    alpha: 'NG',
    alpha3: 'NGA',
    numeric: 566 },
  { name: 'Niue',
    alpha: 'NU',
    alpha3: 'NIU',
    numeric: 570 },
  { name: 'Norfolk Island',
    alpha: 'NF',
    alpha3: 'NFK',
    numeric: 574 },
  { name: 'Northern Mariana Islands',
    alpha: 'MP',
    alpha3: 'MNP',
    numeric: 580 },
  { name: 'Norway',
    alpha: 'NO',
    alpha3: 'NOR',
    numeric: 578 },
  { name: 'Oman',
    alpha: 'OM',
    alpha3: 'OMN',
    numeric: 512 },
  { name: 'Pakistan',
    alpha: 'PK',
    alpha3: 'PAK',
    numeric: 586 },
  { name: 'Palau',
    alpha: 'PW',
    alpha3: 'PLW',
    numeric: 585 },
  { name: 'Palestine',
    alpha: 'PS',
    alpha3: 'PSE',
    numeric: 275 },
  { name: 'Panama',
    alpha: 'PA',
    alpha3: 'PAN',
    numeric: 591 },
  { name: 'Papua New Guinea',
    alpha: 'PG',
    alpha3: 'PNG',
    numeric: 598 },
  { name: 'Paraguay',
    alpha: 'PY',
    alpha3: 'PRY',
    numeric: 600 },
  { name: 'Peru',
    alpha: 'PE',
    alpha3: 'PER',
    numeric: 604 },
  { name: 'Philippines',
    alpha: 'PH',
    alpha3: 'PHL',
    numeric: 608 },
  { name: 'Pitcairn',
    alpha: 'PN',
    alpha3: 'PCN',
    numeric: 612 },
  { name: 'Poland',
    alpha: 'PL',
    alpha3: 'POL',
    numeric: 616 },
  { name: 'Portugal',
    alpha: 'PT',
    alpha3: 'PRT',
    numeric: 620 },
  { name: 'Puerto Rico',
    alpha: 'PR',
    alpha3: 'PRI',
    numeric: 630 },
  { name: 'Qatar',
    alpha: 'QA',
    alpha3: 'QAT',
    numeric: 634 },
  { name: 'Reunion',
    alpha: 'RE',
    alpha3: 'REU',
    numeric: 638 },
  { name: 'Romania',
    alpha: 'RO',
    alpha3: 'ROU',
    numeric: 642 },
  { name: 'Russian Federation',
    alpha: 'RU',
    alpha3: 'RUS',
    numeric: 643 },
  { name: 'Rwanda',
    alpha: 'RW',
    alpha3: 'RWA',
    numeric: 646 },
  { name: 'Saint Barthélemy',
    alpha: 'BL',
    alpha3: 'BLM',
    numeric: 652 },
  { name: 'Saint Helena',
    alpha: 'SH',
    alpha3: 'SHN',
    numeric: 654 },
  { name: 'Saint Kitts and Nevis',
    alpha: 'KN',
    alpha3: 'KNA',
    numeric: 659 },
  { name: 'Saint Lucia',
    alpha: 'LC',
    alpha3: 'LCA',
    numeric: 662 },
  { name: 'Saint Martin (French part)',
    alpha: 'MF',
    alpha3: 'MAF',
    numeric: 663 },
  { name: 'Saint Pierre and Miquelon',
    alpha: 'PM',
    alpha3: 'SPM',
    numeric: 666 },
  { name: 'Saint Vincent and the Grenadines',
    alpha: 'VC',
    alpha3: 'VCT',
    numeric: 670 },
  { name: 'Samoa',
    alpha: 'WS',
    alpha3: 'WSM',
    numeric: 882 },
  { name: 'San Marino',
    alpha: 'SM',
    alpha3: 'SMR',
    numeric: 674 },
  { name: 'Sao Tome and Principe',
    alpha: 'ST',
    alpha3: 'STP',
    numeric: 678 },
  { name: 'Saudi Arabia',
    alpha: 'SA',
    alpha3: 'SAU',
    numeric: 682 },
  { name: 'Senegal',
    alpha: 'SN',
    alpha3: 'SEN',
    numeric: 686 },
  { name: 'Serbia',
    alpha: 'RS',
    alpha3: 'SRB',
    numeric: 688 },
  { name: 'Seychelles',
    alpha: 'SC',
    alpha3: 'SYC',
    numeric: 690 },
  { name: 'Sierra Leone',
    alpha: 'SL',
    alpha3: 'SLE',
    numeric: 694 },
  { name: 'Singapore',
    alpha: 'SG',
    alpha3: 'SGP',
    numeric: 702 },
  { name: 'Slovakia',
    alpha: 'SK',
    alpha3: 'SVK',
    numeric: 703 },
  { name: 'Slovenia',
    alpha: 'SI',
    alpha3: 'SVN',
    numeric: 705 },
  { name: 'Solomon Islands',
    alpha: 'SB',
    alpha3: 'SLB',
    numeric: 90 },
  { name: 'Somalia',
    alpha: 'SO',
    alpha3: 'SOM',
    numeric: 706 },
  { name: 'South Africa',
    alpha: 'ZA',
    alpha3: 'ZAF',
    numeric: 710 },
  { name: 'South Georgia and South Sandwich Islands',
    alpha: 'GS',
    alpha3: 'SGS',
    numeric: 239 },
  { name: 'Spain',
    alpha: 'ES',
    alpha3: 'ESP',
    numeric: 724 },
  { name: 'Sri Lanka',
    alpha: 'LK',
    alpha3: 'LKA',
    numeric: 144 },
  { name: 'Sudan',
    alpha: 'SD',
    alpha3: 'SDN',
    numeric: 736 },
  { name: 'Suriname',
    alpha: 'SR',
    alpha3: 'SUR',
    numeric: 740 },
  { name: 'Svalbard and Jan Mayen Islands',
    alpha: 'SJ',
    alpha3: 'SJM',
    numeric: 744 },
  { name: 'Swaziland',
    alpha: 'SZ',
    alpha3: 'SWZ',
    numeric: 748 },
  { name: 'Sweden',
    alpha: 'SE',
    alpha3: 'SWE',
    numeric: 752 },
  { name: 'Switzerland',
    alpha: 'CH',
    alpha3: 'CHE',
    numeric: 756 },
  { name: 'Syria',
    alpha: 'SY',
    alpha3: 'SYR',
    numeric: 760 },
  { name: 'Taiwan',
    alpha: 'TW',
    alpha3: 'TWN',
    numeric: 158 },
  { name: 'Tajikistan',
    alpha: 'TJ',
    alpha3: 'TJK',
    numeric: 762 },
  { name: 'Tanzania',
    alpha: 'TZ',
    alpha3: 'TZA',
    numeric: 834 },
  { name: 'Thailand',
    alpha: 'TH',
    alpha3: 'THA',
    numeric: 764 },
  { name: 'Timor-Leste',
    alpha: 'TL',
    alpha3: 'TLS',
    numeric: 626 },
  { name: 'Togo',
    alpha: 'TG',
    alpha3: 'TGO',
    numeric: 768 },
  { name: 'Tokelau',
    alpha: 'TK',
    alpha3: 'TKL',
    numeric: 772 },
  { name: 'Tonga',
    alpha: 'TO',
    alpha3: 'TON',
    numeric: 776 },
  { name: 'Trinidad and Tobago',
    alpha: 'TT',
    alpha3: 'TTO',
    numeric: 780 },
  { name: 'Tunisia',
    alpha: 'TN',
    alpha3: 'TUN',
    numeric: 788 },
  { name: 'Turkey',
    alpha: 'TR',
    alpha3: 'TUR',
    numeric: 792 },
  { name: 'Turkmenistan',
    alpha: 'TM',
    alpha3: 'TKM',
    numeric: 795 },
  { name: 'Turks and Caicos Islands',
    alpha: 'TC',
    alpha3: 'TCA',
    numeric: 796 },
  { name: 'Tuvalu',
    alpha: 'TV',
    alpha3: 'TUV',
    numeric: 798 },
  { name: 'Uganda',
    alpha: 'UG',
    alpha3: 'UGA',
    numeric: 800 },
  { name: 'Ukraine',
    alpha: 'UA',
    alpha3: 'UKR',
    numeric: 804 },
  { name: 'United Arab Emirates',
    alpha: 'AE',
    alpha3: 'ARE',
    numeric: 784 },
  { name: 'United Kingdom',
    alpha: 'GB',
    alpha3: 'GBR',
    numeric: 826 },
  { name: 'United States Minor Outlying Islands',
    alpha: 'UM',
    alpha3: 'UMI',
    numeric: 581 },
  { name: 'United States of America',
    alpha: 'US',
    alpha3: 'USA',
    numeric: 840 },
  { name: 'Uruguay',
    alpha: 'UY',
    alpha3: 'URY',
    numeric: 858 },
  { name: 'Uzbekistan',
    alpha: 'UZ',
    alpha3: 'UZB',
    numeric: 860 },
  { name: 'Vanuatu',
    alpha: 'VU',
    alpha3: 'VUT',
    numeric: 548 },
  { name: 'Vatican City',
    alpha: 'VA',
    alpha3: 'VAT',
    numeric: 336 },
  { name: 'Venezuela',
    alpha: 'VE',
    alpha3: 'VEN',
    numeric: 862 },
  { name: 'Vietnam',
    alpha: 'VN',
    alpha3: 'VNM',
    numeric: 704 },
  { name: 'Virgin Islands, British',
    alpha: 'VG',
    alpha3: 'VGB',
    numeric: 92 },
  { name: 'Virgin Islands, U.S.',
    alpha: 'VI',
    alpha3: 'VIR',
    numeric: 850 },
  { name: 'Wallis and Futuna Islands',
    alpha: 'WF',
    alpha3: 'WLF',
    numeric: 876 },
  { name: 'Western Sahara',
    alpha: 'EH',
    alpha3: 'ESH',
    numeric: 732 },
  { name: 'Yemen',
    alpha: 'YE',
    alpha3: 'YEM',
    numeric: 887 },
  { name: 'Zambia',
    alpha: 'ZM',
    alpha3: 'ZMB',
    numeric: 894 },
  { name: 'Zimbabwe',
    alpha: 'ZW',
    alpha3: 'ZWE',
    numeric: 716 } ]
